CXX=g++
CXXFLAGS=-std=c++11
twospherescollision: twospherescollision.cpp ../composedSpheresCB.cpp ../collisionResolve.cpp ../collisionBody.cpp 
	$(CXX) twospherescollision.cpp ../composedSpheresCB.cpp ../collisionResolve.cpp ../collisionBody.cpp -o twospherescollision $(CXXFLAGS)
